### ISSUE TITLE
error since 2.2.3

### ISSUE THREAD

**Issue by stockhausen** [anomalylabs/navigation-module#30]
Hello, 

since 2.2.3, 

`{{ menu('menu').listClass('list list-unstyled').childListClass('dropdown-menu').render()|raw }}`

got this error 
`An exception has been thrown during the rendering of a template ("Undefined index: path")`

bonne fin de semaine.

Fab.

**Comment by stockhausen** [comment]
ok only when item inside menu is URL

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/navigation-module/commit/0ade6bde9728838f33ac70f8ca7bc80d8c202bed
