### ISSUE TITLE
[Feature] Add "Show to Authenticated users only"

### ISSUE THREAD

**Issue by agustindidiego** [anomalylabs/navigation-module#34]
Add new boolean field to show links to authenticated users only.
Currently you can specify to which User Roles a link can be shown to, but, could be nice to have an option to specify that a certain link just need an authenticated user to be shown, independently of his User Role.

**Comment by RyanThompson** [comment]
This is in the wrong repository :-(

In this case I would lean heavily the the direction of selecting all roles ^_^
